import React, { useState, useEffect } from "react";
import Head from "next/head";
import * as S from "@/styles/home";
import NavBar from "@/components/Navbar";
import CampeonatoInfo from "@/components/CampeonatoInfo";
import CampeonatoLista from "@/components/CampeonatoLista";
import Time from "./times";

const Home = () => {
  const [ligaSelecionada, setLigaSelecionada] = useState<{ nome: string; id: number, logo: string } | null>(null);
  const [timeSelecionado, setTimeSelecionado] = useState<number | null>(null);

  return (
    <>
      <Head>
        <title>Menu Principal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <NavBar />
      <S.Main>
        <S.ContainerPrincipal>
          <S.ContainerLigas>
            <CampeonatoLista onLigaSelect={setLigaSelecionada} />
          </S.ContainerLigas>
          <S.ContainerSecundario>
            {timeSelecionado ? (
              <Time id={timeSelecionado} onBack={() => setTimeSelecionado(null)} />
            ) : ligaSelecionada ? (
              <CampeonatoInfo
                nome={ligaSelecionada.nome}
                id={ligaSelecionada.id}
                logo={ligaSelecionada.logo}
                onSelectTime={setTimeSelecionado}
              />
            ) : (
              <S.SpanPrincipal>Seja bem vindo! Selecione uma liga para visualizar as informações.</S.SpanPrincipal>
            )}
          </S.ContainerSecundario>
        </S.ContainerPrincipal>
      </S.Main>
    </>
  );
};

export default Home;