import React, { useState, useEffect } from "react";
import Head from "next/head";
import * as S from "@/styles/home";
import { CircularProgress } from '@mui/material';
import NavBar from "@/components/Navbar";
import CampeonatoInfo from "@/components/CampeonatoInfo";
import { ILiga } from "@/common/interfaces/liga";
import { LigaApiService } from "@/api/liga";
import Flag from "react-world-flags";
import { getCode } from "country-list";

const Home = () => {
  const [ligas, setLigas] = useState<ILiga[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [ligaSelecionada, setLigaSelecionada] = useState<{ nome: string; id: number, logo: string } | null>(null);

  const formatarParaURL = (texto: string): string => {
    return encodeURIComponent(texto); 
  };

  useEffect(() => {
    const fetchLigas = async () => {
      try {
        const response = await LigaApiService.getAll();
        setLigas(response.data.ligas);
        setLoading(false);
      } catch (err) {
        setError("Erro ao carregar as ligas");
        setLoading(false);
      }
    };

    fetchLigas();
  }, []);

  const handleLigaClick = (liga: ILiga) => {
    const nomeCodificado = formatarParaURL(liga.nome || ""); 
    setLigaSelecionada({ nome: nomeCodificado, id: liga.id, logo: liga.logo??"" }); 
  };

  const getCountryCode = (countryName: string): string => {
    return getCode(countryName) || ""; 
  };

  return (
    <>
      <Head>
        <title>Menu Principal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <NavBar />
      <S.Main>
        <S.ContainerPrincipal>
          <S.ContainerLigas>
            <S.SpanCampeonatos>Campeonatos</S.SpanCampeonatos>
            {loading && <p style={{ color: "white" }}><CircularProgress size={24} color="inherit" /></p>}
            {error && <p>{error}</p>}
            {!loading && !error && ligas.length > 0 && (
              <S.ListaLigas>
                {ligas.map((liga) => (
                  <S.Liga key={liga.id}>
                    <S.LinkLiga onClick={() => handleLigaClick(liga)}>
                      <Flag
                        code={getCountryCode(liga.pais || "")} 
                        style={{ width: 20, height: 15, marginRight: 8 }}
                      />
                      {liga.nome}
                    </S.LinkLiga>
                  </S.Liga>
                ))}
              </S.ListaLigas>
            )}
            {!loading && !error && ligas.length === 0 && <p>Nenhuma liga encontrada.</p>}
          </S.ContainerLigas>
          <S.ContainerSecundario>
            {ligaSelecionada ? (
              <CampeonatoInfo nome={ligaSelecionada.nome} id={ligaSelecionada.id} pais={""} logo={ligaSelecionada.logo} />
            ) : (
              <S.SpanPrincipal>Seja bem vindo! Selecione uma liga para visualizar as informações.</S.SpanPrincipal>
            )}
          </S.ContainerSecundario>
        </S.ContainerPrincipal>
      </S.Main>
    </>
  );
};

export default Home;