import React, { useState } from 'react';
import Head from 'next/head';
import * as S from '../styles/login';
import NavBar from '@/components/Navbar';
import axios from 'axios';
import { useRouter } from 'next/router';

const Home = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const router = useRouter();

  const handleLogin = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    try {
      const response = await axios.post('/api/login', { email, password });
      console.log('Login bem-sucedido:', response.data);
    } catch (error) {
      console.error('Erro no login:', error);
    }
  };

  const goToCadastro = () => {
    router.push('/cadastro');
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <NavBar />
      <S.Main>
        <S.ContainerPrincipal>
          <S.SpanPrincipal>Login</S.SpanPrincipal>
          <S.FormContainer onSubmit={handleLogin}>
            <div>
              <label htmlFor="email">E-mail:</label>
              <input
                type="email"
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                placeholder="Digite seu e-mail"
              />
            </div>
            <div>
              <label htmlFor="password">Senha:</label>
              <input
                type="password"
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                placeholder="Digite sua senha"
              />
            </div>
            <button type="submit">Entrar</button>
          </S.FormContainer>
          <button onClick={goToCadastro} style={{ marginTop: '1rem' }}>
            Fazer Cadastro
          </button>
        </S.ContainerPrincipal>
      </S.Main>
    </>
  );
};

export default Home;
